# -*- coding: utf-8 -*-
"""week1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w-3mlUCnNCUIyWHIz39ROgRqpEcNlVvw
"""

def read_input(filename):
    left = []
    right = []
    with open(filename, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            a, b = line.split()
            left.append(int(a))
            right.append(int(b))
    return left, right


def part1_total_distance(left, right):
    left_sorted = sorted(left)
    right_sorted = sorted(right)

    total = 0
    for a, b in zip(left_sorted, right_sorted):
        total += abs(a - b)
    return total


def part2_similarity_score(left, right):

    counts = {}
    for x in right:
        if x in counts:
            counts[x] += 1
        else:
            counts[x] = 1

    total = 0
    for x in left:
        times = counts.get(x, 0)
        total += x * times
    return total


def main():
    left, right = read_input("input.txt")

    answer1 = part1_total_distance(left, right)
    answer2 = part2_similarity_score(left, right)

    print("Part 1 (total distance):", answer1)
    print("Part 2 (similarity score):", answer2)


if __name__ == "__main__":
    main()